##### Example config for training a GAE ####
dataset: data/REDDIT-MULTI-5K/
model:
  gnn_type: gae
  num_layers: 6
  nlayer_inner: 1
  pool: add
  bn: False 
  res: False
  exp_after: False
  laplacian: False
  hidden_size: 100
  transform: None
  EMBED_SIZE: 40
  nout: 1 #3
embed_model: None
train:
  epochs: 100
  batch_size: 10
  num_samples: 1
  num_workers: 8
  lr: 0.006
test:
  num_samples: samples_only
model_path: ./NODE_MODELS/gae2-decoderzzt.pth # Save model path
wandb: False
regression: gae
gae: True # Training a GAE