### Example config for training a model on random input ONLY
dataset: ZINC
model:
  gnn_type: samples_only  #whether or not we are only training on random input
  num_layers: 6 # Number of gconv layers
  nlayer_inner: 1
  pool: mean
  bn: False # Batchnorm not used right now anyways
  res: False # If true, uses residual connections. If false, uses skip connections
  exp_after: False
  laplacian: False
  hidden_size: 100
  transform: None
  EMBED_SIZE: 15 # This controls the node embedding size that is eventually used in the 2nd round of training.
  nout: 1 
embed_model: None
train:
  epochs: 170
  batch_size: 100
  num_samples: 80 
  # Number of random samples. If only training on attributes or if this is the 2nd round of training, set to None
  num_workers: 8
  lr: 0.0001
test:
  num_samples: samples_only
model_path: None # path to save the model (used to get embeddings in second round of training)
wandb: False
regression: R 
# If we are using the Zinc dataset, we are training on graph regression. M and B are for multi-class and binary classification.
gae: False # Whether or not we are training a GAE
