##### Example config for training a GAE ####
dataset: ZINC
model:
  gnn_type: gae
  num_layers: 6
  nlayer_inner: 1
  pool: add
  bn: False 
  res: False
  exp_after: False
  laplacian: False
  hidden_size: 100
  transform: None
  EMBED_SIZE: 40
  nout: 1 #3
embed_model: None
train:
  epochs: 100
  batch_size: 30
  num_samples: 90
  num_workers: 8
  lr: 0.0001
test:
  num_samples: samples_only
model_path: ./NODE_MODELS/gae2-decoderzzt.pth # Save model path
wandb: True
regression: gae
gae: True # Training a GAE