dataset: ZINC
model:
  # gnn_type: PPGN
  # num_layers: 1
  # nlayer_inner: 4
  # pool: add

  gnn_type: Random
  num_layers: 8
  nlayer_inner: 1
  pool: add
train:
  epochs: 450
  num_samples: 100
  dropout: 0.4
test:
  num_samples: 100